name: clean_logging
version: 0.2.0
author: Clean Team <clean@vacuumlabs.com>
description: Structured logging library for Dart.
homepage: https://github.com/cleandart/clean_logging
environment:
  sdk: '>=0.8.10+6 <2.0.0'
documentation: https://github.com/cleandart/clean_logging
dependencies:
  browser: '>=0.10.0+1 <0.11.0'
  clean_ajax: '>=0.4.7 <0.5.0'
  http_server: '>=0.9.2 <0.10.0'
  logging: '>=0.9.0 <0.10.0'
  mongo_dart: '>=0.1.39 <0.2.0'
